### PR TITLE
Adds announcement of Arquillian Cube Alpha20

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Aren't we missing A19 as well? :)

**Comment by lordofthejars** [comment]
yes :( do you want I create it? I said this to not publish in same day two versions.

**Comment by bartoszmajsak** [comment]
Is there anything significant there?

**Comment by bartoszmajsak** [comment]
Upstream @244ae1b75661977229101866c3051f2ee2515cbb

**Pull request closed without merging**
