### PR TITLE
blog: release notes for Smart Testing 0.0.4

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Comment by alien-ike** [comment]
### Blog Preview
blog-preview

**Comment by bartoszmajsak** [comment]
[Failing test is rather strange](https://travis-ci.org/arquillian/arquillian.github.io/builds/302677152#L3143), as locally I see it correct. Are we testing here against prod?

**Comment by bartoszmajsak** [comment]
image

Generated using `awestruct -d`... Any idea @MatousJobanek?

**Comment by bartoszmajsak** [comment]
- [ ] Add reference to the build number in the comment sent by bot
- [ ] Improve shell script in case multiple blog files changed
- [ ] UI tests should publish screenshots on failure

**Comment by alien-ike** [comment]
### Blog Preview
blog-preview

**Comment by alien-ike** [comment]
### Blog Preview
blog-preview

**Comment by alien-ike** [comment]
### Blog Preview
[Build 130](https://travis-ci.org/arquillian/arquillian.github.io/builds/302892132

blog-preview

**Comment by alien-ike** [comment]
### Blog Preview
[Build 132](https://travis-ci.org/arquillian/arquillian.github.io/builds/302908031)

blog-preview

**Comment by alien-ike** [comment]
### Blog Preview
[Build 135](https://travis-ci.org/arquillian/arquillian.github.io/builds/302947914)

blog-preview

**Comment by bartoszmajsak** [comment]
Let's hold this PR until we sort out 1.1.14.Final release problem

**Pull request merged**
