### PR TITLE
docs(release): Arquillian Cube 1.5.1 release announcement

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
If that's only one sentence I think the autogenerated release notes are enough. WDYT?

**Comment by lordofthejars** [comment]
yes, I have checked now, I thought only issues where shown.

**Comment by bartoszmajsak** [comment]
Then there is no need to have this file at all, except if you want to be there as an author :)

**Comment by lordofthejars** [comment]
I think the file is required.

**Comment by bartoszmajsak** [comment]
Trust me, it's not :)

**Pull request closed without merging**
