### PR TITLE
blog: Smart Testing 0.0.8 announcement

### PR DESCRIPTION
**Pull request by MatousJobanek**
image

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
@MatousJobanek I'm missing the description of the behaviour for @categorized@ strategy - we only explain @failed@.

**Comment by bartoszmajsak** [comment]
I am not sure if it is obvious. Does it mean I can put @Category on the method level?

**Comment by MatousJobanek** [comment]
I added the description of the `categorized` strategy. Now it looks like this:
image

**Comment by bartoszmajsak** [comment]
That's helpful (for dummies like me).  Thank you!

**Pull request merged**
